# Generated by Django 4.2.10 on 2026-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('selected_route', models.JSONField(help_text='Coordinates of the selected route')),
                ('safety_score', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('time_of_day', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('police_station', 'Police Station'), ('hospital', 'Hospital'), ('public_place', 'Public Place'), ('well_lit', 'Well-Lit Area'), ('cctv', 'CCTV Coverage')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField(default=500, help_text='Safety radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrimePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('harassment', 'Harassment'), ('vandalism', 'Vandalism'), ('burglary', 'Burglary'), ('other', 'Other')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_sample_data', models.BooleanField(default=False)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='safe_route__occurre_22c9bd_idx'), models.Index(fields=['crime_type'], name='safe_route__crime_t_2ecd27_idx')],
            },
        ),
    ]
