# Generated by Django 4.2.10 on 2026-01-10 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('safe_route_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAuthority',
            fields=[
                ('firebase_uid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=100)),
                ('jurisdiction_area', models.CharField(max_length=200)),
                ('jurisdiction_lat', models.FloatField()),
                ('jurisdiction_lng', models.FloatField()),
                ('jurisdiction_radius', models.IntegerField(default=5000)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('firebase_uid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('emergency_contact_1_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_1_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_2_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_2_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('start_address', models.CharField(max_length=500)),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_address', models.CharField(max_length=500)),
                ('distance_km', models.FloatField()),
                ('duration_minutes', models.IntegerField()),
                ('safety_score', models.CharField(max_length=1)),
                ('route_data', models.JSONField()),
                ('ride_service', models.CharField(blank=True, max_length=20, null=True)),
                ('ride_booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('video_enabled', models.BooleanField(default=False)),
                ('video_urls', models.JSONField(default=list)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_evidence', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safe_route_app.policeauthority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='safe_route_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='policeauthority',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_profile', to='safe_route_app.userprofile'),
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_latitude', models.FloatField()),
                ('alert_longitude', models.FloatField()),
                ('alert_address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('video_clips', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safe_route_app.policeauthority')),
                ('travel_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_route_app.travelhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='safe_route_app.userprofile')),
            ],
            options={
                'ordering': ['-alert_time'],
            },
        ),
        migrations.AddIndex(
            model_name='travelhistory',
            index=models.Index(fields=['user', '-created_at'], name='safe_route__user_id_7605b2_idx'),
        ),
        migrations.AddIndex(
            model_name='travelhistory',
            index=models.Index(fields=['expires_at'], name='safe_route__expires_977bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status', '-alert_time'], name='safe_route__status_4707ee_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['assigned_officer', 'status'], name='safe_route__assigne_fa971f_idx'),
        ),
    ]
