# Generated by Django 5.1.4 on 2026-01-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_route_app', '0002_policeauthority_userprofile_travelhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeauthority',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policeauthority',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policeauthority',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policeauthority',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SafetyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'General Info'), ('medium', 'Advisory'), ('high', 'Safety Alert'), ('critical', 'Emergency')], default='low', max_length=20)),
                ('region_tag', models.CharField(blank=True, help_text="e.g., 'Downtown', 'Indiranagar'", max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL to image in Firebase Storage', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_route_app.policeauthority')),
            ],
            options={
                'verbose_name_plural': 'Safety News',
                'ordering': ['-created_at'],
            },
        ),
    ]
