# Generated by Django 4.2.10 on 2026-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_route_app', '0003_policeauthority_current_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
